Smaller strum note code
ShadowMario/FNF-PsychEngine pull request #10643
Opened 2022-09-24 16:23 UTC by MaybeMaru

Made it a bit smaller and also fixed the pixel strums framerate

2022-09-24 21:27 UTC, MemeHoovy approved these changes

2022-09-24 21:34 UTC, Luisinhi010 approved these changes

2022-09-24 23:52 UTC, kingyomoma requested changes

2022-09-24 23:52 UTC, kingyomoma commented on source/FunkinLua.hx
> +			return color;
this would return a FlxColor object
`return FlxColor.toHexString(color, false);` would probably work instead

2022-09-25 18:09 UTC, TinyGamesCoding commented
this is radically radical

2022-09-25 18:11 UTC, xLinkmain approved these changes
Yes

2022-09-25 18:13 UTC, TinyGamesCoding approved these changes

2022-09-25 18:14 UTC, BlueColorsin commented
Holy shit it is swag

2022-09-25 18:14 UTC, BlueColorsin approved these changes

2022-09-25 18:58 UTC, kingyomoma approved these changes

2022-09-25 21:42 UTC, Raltyro approved these changes

2022-09-26 11:47 UTC, JorosTheModderPH approved these changes

2022-09-26 12:44 UTC, MemeHoovy approved these changes

2022-09-28 17:11 UTC, cyn-8 approved these changes

2022-09-28 18:49 UTC, TheKitBoi approved these changes

2022-09-29 04:02 UTC, ImaginationSuperHero528 approved these changes

2022-09-29 12:30 UTC, Parsellol approved these changes

2022-09-30 03:34 UTC, LEVIXDDLMAO commented
dope

2022-10-01 04:54 UTC, ImaginationSuperHero528 approved these changes

2022-10-17 16:11 UTC, MaybeMaru commented
looking back this is a kinda trashy pr, soooo cya

2022-10-17 16:11 UTC, closed without merging