Added onExitSong function and exitingsong variable
ShadowMario/FNF-PsychEngine pull request #11000
Opened 2022-10-25 20:25 UTC by KirbyKid256

These would be triggered SPECIFICALLY when you exit the current week rather than just when the script is destroyed (which happens whenever you end, restart, or exit the song).

2022-10-25 20:29 UTC, MemeHoovy reviewed
iirc I think lua has a destroy thing, where a script is triggered whenever the script is destroyed, so isn't that everytime a song ends/exits? in that case this makes this useless

2022-10-25 21:13 UTC, KirbyKid256 commented
> iirc I think lua has a destroy thing, where a script is triggered whenever the script is destroyed, so isn't that everytime a song ends/exits? in that case this makes this useless

Yes, but "everytime" includes restarting the song, ending the song, exiting the song, going back in time with Skip Time in Charting State, entering the Chart Editor, and entering the Character Editor. This addition would make it so that it's ONLY triggered when you're basically transitioning from PlayState to StoryMenuState or FreeplayState. And while the onExitSong is triggered the moment you start to exit the song, you can also use exitingsong with onDestroy when the script is destroyed because you're exiting the song.
For example: `function onDestroy()
if getProperty("exitingsong") then
--[[code here]]
end
end`

2022-10-30 07:38 UTC, CoolingTool requested changes
should opening the chart editor really count as exiting? also i think `exitingsong` should be camel cased like pretty much every other variable

2022-11-02 17:38 UTC, KirbyKid256 commented
> should opening the chart editor really count as exiting? also i think `exitingsong` should be camel cased like pretty much every other variable

For the first one, I could make a different callOnLuas like "onOpenChartEditor" or something like that. For the second one, I somehow read the endingSong variable as all lowercase which was why I made exitingSong all lowercase. I'll definitely fix that one.

2022-11-03 16:40 UTC, TheKitBoi approved these changes

2022-11-12 19:21 UTC, BombasticTomDev approved these changes
Decent changes, could help modders in the future.

2022-11-15 23:27 UTC, CoolingTool approved these changes

2023-01-07 14:41 UTC, closed without merging