callFromObject & callFromClass
ShadowMario/FNF-PsychEngine pull request #11314
Opened 2022-11-25 22:27 UTC by Cherif107

cause it would be so useful for some cases

2022-11-26 01:10 UTC, ShadowMilky approved these changes

2022-11-26 05:37 UTC, system32unknown commented
how `callFromClass` is works?

2022-11-26 07:48 UTC, system32unknown requested changes
change `arguments:Array<Dynamic>` to `?arguments:Array<Dynamic>`,
then put `
    if (arguments != null) 
        arguments = [];
`

2022-11-26 11:04 UTC, Raltyro approved these changes

2022-11-26 15:40 UTC, TheKitBoi approved these changes

2022-11-27 06:55 UTC, DisIsNOt approved these changes

2022-11-28 11:10 UTC, system32unknown approved these changes

2022-12-01 13:40 UTC, ImaginationSuperHero528 approved these changes

2022-12-27 19:09 UTC, ImaginationSuperHero528 approved these changes

2023-01-09 17:45 UTC, MaybeMaru approved these changes

2023-02-17 14:32 UTC, YanniZ06 requested changes
Why would you name the variables like that pleaseeee
how hard is it to make proper readable variable names

2023-04-28 17:24 UTC, closed without merging