Simplified Paths.hx
ShadowMario/FNF-PsychEngine pull request #12313
Opened 2023-04-23 21:59 UTC by Joalor64GH

It's pretty self-explanatory.

2023-04-23 22:04 UTC, MemeHovy reviewed
@Joalor64GH the main reason those are two separate things is because it'll return a different type if it is done like this, that's the main pet peeve I have with haxe but that's how it works though, believe me, I've tried before

2023-04-23 22:04 UTC, MemeHovy commented
unless you add the return type however

2023-04-23 22:06 UTC, MemeHovy requested changes

2023-04-23 22:06 UTC, MemeHovy commented on source/Paths.hx
>  	inline static function getLibraryPathForce(file:String, library:String, ?level:String)
make sure to add the return types for some of these, otherwise it'll throw errors, cuz the compiler will auto assign an type to it

2023-04-23 22:08 UTC, MemeHovy requested changes
returnGraphic doesn't have a type assigned to it so it'll be automatically assigned, likely to cause errors

2023-04-24 10:38 UTC, CaptainBaldi commented
Most of these changes are completely useless

2023-04-24 20:05 UTC, MemeHovy commented
> Most of these changes are completely useless

that aswell

2023-04-24 21:30 UTC, KookerFoxYT commented
> Most of these changes are completely useless

agreed

2023-04-24 21:31 UTC, KookerFoxYT commented
i mean like, it isnt that much more simplified than what one can do to simplify ClientPrefs

2023-07-31 14:30 UTC, closed without merging