include classes which not used in game
ShadowMario/FNF-PsychEngine pull request #12848
Opened 2023-07-25 20:12 UTC by TheLeerName

hscript: 📈

for example u cant `addHaxeLibrary('FlxGlitchEffect', 'flixel.addons.effects.chainable')` if source code not used this class

previous pr was for experimental branch: #12733

2023-07-25 20:44 UTC, MemeHovy approved these changes

2023-07-25 23:56 UTC, ActualMandM requested changes
This currently runs into this error on compilation: `D:\Programs\HaxeToolkit\haxe\std/haxe/atomic/AtomicObject.hx:8: characters 8-58 : JavaScript and Hxcpp do not support AtomicObject`

2023-07-25 23:56 UTC, ActualMandM commented on source/macros/AdditionalClasses.hx
> +			"haxe.macro",
```suggestion
			"haxe.macro",
			#if (js || hxcpp) "haxe.atomic.AtomicObject", #end
```

2023-07-26 07:20 UTC, ActualMandM approved these changes

2023-07-26 10:44 UTC, TheLeerName commented
omg sscript broken

2023-07-31 14:19 UTC, TheLeerName commented
#12953

2023-07-31 14:19 UTC, closed without merging