Target Zoom for Cameras in PlayState
ShadowMario/FNF-PsychEngine pull request #15775
Opened 2024-10-21 17:09 UTC by AlsoGhostglowDev

cameras in playstate now uses `PsychCamera` which now has the `targetZoom` field that can be used to manipulate default camera zooms for the hud camera and game camera (defaultCamZoom still works for camGame) but this is mostly done for the hud camera

2024-11-23 04:49 UTC, 2JENO requested changes
cmd saying:
 
 return camGame.targetZoom = defaultCamZoom = value;
  |                                                 ^^^^^^^^^^^^
  | This field cannot be accessed because it is not a real variable
 public var defaultCamZoom(get, set):Float;
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 | Add @:isVar here to enable it

2024-11-23 04:58 UTC, 2JENO commented
add "@:isVar" over "public var defaultCamZoom(get, set):Float;"

2024-11-23 05:02 UTC, 2JENO commented
Called from states.PlayState::set_camZoomingDecay states/PlayState.hx line 165
Critical Error: Uncatchable Throw: Null Object Reference

2024-11-27 03:19 UTC, AlsoGhostglowDev commented
@2JENO yo, didnt see this comment. Sorry for the late response. I'll get into this when I'm return home 👻

2025-03-31 15:30 UTC, closed without merging