Fully Functioning, Stylish, Robust, Stage Editor.
ShadowMario/FNF-PsychEngine pull request #3502
Opened 2022-01-13 02:06 UTC by magnumsrtisswag

###**What the funk is this??**

What else is to be said, you can add layers, scale them (this'll fuck up your x and y axis a bit so beware), you can add scroll factors for those layers, move them, and more! The stage editor is also stylish and easy to use, not to mention it's memory friendly!
____________________________________________________________________________
### **Why you should merge**
Is that a serious question? People have been asking for this for ages!
____________________________________________________________________________
Thanks for your consideration.

2022-01-13 02:32 UTC, HiroMizuki commented
there's just some things that's not helping, like, the deleted lines of achievement file and etc
i understand ya, maybe u were using a older version of the source, but i'd recommend to edit it

2022-01-13 03:08 UTC, magnumsrtisswag commented
> maybe transport ur stage editor code to the most recent version of psych engine yknow

just did 👍

2022-01-13 03:20 UTC, HiroMizuki commented
> > maybe transport ur stage editor code to the most recent version of psych engine yknow
> 
> just did 👍

nice dude lmao

2022-01-13 03:23 UTC, HiroMizuki commented
shaders and strum notes angle correction at PR was still deleted
but at rest, it's a good PR
maybe i'll aproove it

2022-01-13 03:37 UTC, CrusherMods commented
![image](https://user-images.githubusercontent.com/90648119/149261533-02be3400-5b5d-48ba-bf38-4ff60a5d667a.png)
???????????????????????

2022-01-13 03:41 UTC, HiroMizuki commented
> ![image](https://user-images.githubusercontent.com/90648119/149261533-02be3400-5b5d-48ba-bf38-4ff60a5d667a.png) ???????????????????????

he forgot to port the shaders too, temporary issue

2022-01-13 03:42 UTC, magnumsrtisswag commented
gonna close this since pull requests are disabled till next update, and i have some port issues to fix.

2022-01-13 13:49 UTC, magnumsrtisswag commented
alright people are mad that i closed so i reopened it BUT SHADOW MARIO WON'T MERGE SINCE THEY ARE CLOSED TILL NEXT UPDATE KEEP THAT IN MIND

2022-01-13 13:51 UTC, magnumsrtisswag commented
and it compiles now

2022-01-13 15:46 UTC, trayfellow commented
real

2022-01-13 16:06 UTC, DEMOLITIONDON96 commented
Daaamn, this is nice, mind if I use the code?

2022-01-13 17:14 UTC, Stilic commented
Now port this to Mag Engine @magnumsrtisswag.

2022-01-14 00:05 UTC, pakieFNF commented
FUCK YEA LET'S GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2022-01-14 10:48 UTC, Doritojoey approved these changes
I think this is pretty good but some weird changes with achievements and stuff, etc etc. Relatively good and it looks like you're ironing this out anyway so it's neat and definitely useful.

2022-01-14 13:38 UTC, magnumsrtisswag commented
> I think this is pretty good but some weird changes with achievements and stuff, etc etc. Relatively good and it looks like you're ironing this out anyway so it's neat and definitely useful.

The reason most of the code was changed at the start is because I was using an outdated version of the source which I have now fixed.

2022-01-14 15:34 UTC, HiroMizuki approved these changes
forgot to approve lmao

2022-01-14 16:13 UTC, stilic approved these changes

2022-01-14 16:29 UTC, fireredfan7 approved these changes
This has been long over-do.

2022-01-14 20:07 UTC, nintendofan44 approved these changes
i approve

2022-01-14 20:38 UTC, Stilic commented
@bbpanzu Ayo? (deluxe)

2022-01-15 03:57 UTC, XtraXD1 commented
["It's
fucking
approved"](https://youtu.be/dhO0m96NXzk)
(By the way please @ShadowMario and Dev team approve it)

2022-01-15 12:34 UTC, Doritojoey commented
> > I think this is pretty good but some weird changes with achievements and stuff, etc etc. Relatively good and it looks like you're ironing this out anyway so it's neat and definitely useful.
> 
> The reason most of the code was changed at the start is because I was using an outdated version of the source which I have now fixed.

Yeah I was aware of that. But yeah you are fixing it so I commend it. Good work

2022-01-16 04:43 UTC, trayfellow approved these changes

2022-01-16 17:04 UTC, JorgeMiguel22 commented
how do i add it, cuz im new to github

2022-01-16 17:44 UTC, HiroMizuki commented
> source/Achievements.hx:172: characters 95-104 : Type not found : PlayState source/Achievements.hx:183: characters 119-128 : Type not found : PlayState source/CoolUtil.hx:30: characters 25-34 : Type not found : PlayState source/CoolUtil.hx:46: characters 23-32 : Type not found : PlayState source/WeekData.hx:192: characters 9-18 : Type not found : PlayState source/WeekData.hx:223: characters 20-29 : Type not found : PlayState source/WeekData.hx:228: characters 36-45 : Type not found : PlayState source/FreeplayState.hx:58: characters 3-12 : Type not found : PlayState source/FreeplayState.hx:438: characters 3-12 : Type not found : PlayState source/FreeplayState.hx:377: characters 3-12 : Type not found : PlayState source/FreeplayState.hx:294: characters 5-19 : Type not found : PlayState source/FreeplayState.hx:295: characters 9-23 : Type not found : PlayState source/FreeplayState.hx:301: characters 37-51 : Type not found : PlayState source/FreeplayState.hx:326: characters 4-18 : Type not found : PlayState source/FreeplayState.hx:327: characters 4-13 : Type not found : PlayState source/FreeplayState.hx:328: characters 4-13 : Type not found : PlayState source/FreeplayState.hx:338: characters 41-50 : Type not found : PlayState source/editors/StageEditorState.hx:439: characters 48-57 : Type not found : PlayState source/animateatlas/AtlasFrameMaker.hx:72: characters 6-15 : Type not found : PlayState source/editors/CharacterEditorState.hx:1120: characters 37-46 : Type not found : PlayState source/LoadingState.hx:68: characters 9-23 : Type not found : PlayState source/LoadingState.hx:140: characters 21-35 : Type not found : PlayState source/LoadingState.hx:145: characters 23-37 : Type not found : PlayState source/StoryMenuState.hx:59: characters 3-12 : Type not found : PlayState source/StoryMenuState.hx:398: characters 3-12 : Type not found : PlayState source/StoryMenuState.hx:294: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:295: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:301: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:303: characters 4-18 : Type not found : PlayState source/StoryMenuState.hx:304: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:305: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:308: characters 41-50 : Type not found : PlayState source/StrumNote.hx:48: characters 6-15 : Type not found : PlayState source/StrumNote.hx:159: characters 47-56 : Type not found : PlayState source/StrumNote.hx:37: characters 6-20 : Type not found : PlayState source/StrumNote.hx:138: characters 46-55 : Type not found : PlayState source/editors/ChartingState.hx:197: characters 7-21 : Type not found : PlayState source/Note.hx:126: characters 36-66 : Type not found : PlayState source/Note.hx:126: characters 69-86 : Type not found : PlayState source/Note.hx:126: characters 8-92 : Cannot add Void and Int source/Note.hx:231: characters 11-25 : Type not found : PlayState source/Note.hx:247: characters 6-15 : Type not found : PlayState source/Note.hx:184: characters 8-17 : Type not found : PlayState source/Note.hx:202: characters 8-17 : Type not found : PlayState source/Note.hx:207: characters 8-17 : Type not found : PlayState source/Note.hx:214: characters 7-16 : Type not found : PlayState source/Note.hx:82: characters 23-37 : Type not found : PlayState source/editors/ChartingState.hx:2632: characters 3-17 : Type not found : PlayState source/editors/ChartingState.hx:423: characters 4-18 : Type not found : PlayState source/editors/ChartingState.hx:573: characters 14-28 : Type not found : PlayState source/editors/ChartingState.hx:1534: characters 5-19 : Type not found : PlayState source/editors/ChartingState.hx:1540: characters 41-50 : Type not found : PlayState source/Shaders.hx:279: characters 3-12 : Type not found : PlayState source/Shaders.hx:461: characters 4-13 : Type not found : PlayState source/Shaders.hx:1002: characters 3-12 : Type not found : PlayState source/Shaders.hx:1048: characters 3-12 : Type not found : PlayState source/Shaders.hx:1098: characters 3-12 : Type not found : PlayState source/FunkinLua.hx:92: characters 14-28 : Type not found : PlayState source/FunkinLua.hx:93: characters 22-36 : Type not found : PlayState source/FunkinLua.hx:97: characters 19-33 : Type not found : PlayState source/FunkinLua.hx💯 characters 22-31 : Type not found : PlayState source/FunkinLua.hx:101: characters 21-30 : Type not found : PlayState source/FunkinLua.hx:102: characters 18-27 : Type not found : PlayState source/FunkinLua.hx:103: characters 34-43 : Type not found : PlayState source/FunkinLua.hx:104: characters 23-32 : Type not found : PlayState source/FunkinLua.hx:136: characters 25-34 : Type not found : PlayState source/FunkinLua.hx:137: characters 25-34 : Type not found : PlayState source/FunkinLua.hx:138: characters 26-35 : Type not found : PlayState source/FunkinLua.hx:139: characters 18-27 : Type not found : PlayState source/FunkinLua.hx:140: characters 19-28 : Type not found : PlayState source/FunkinLua.hx:150: characters 28-37 : Type not found : PlayState source/FunkinLua.hx:151: characters 28-37 : Type not found : PlayState source/FunkinLua.hx:152: characters 27-36 : Type not found : PlayState source/FunkinLua.hx:153: characters 27-36 : Type not found : PlayState source/FunkinLua.hx:154: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:155: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:158: characters 24-38 : Type not found : PlayState source/FunkinLua.hx:159: characters 18-32 : Type not found : PlayState source/FunkinLua.hx:160: characters 17-31 : Type not found : PlayState source/FunkinLua.hx:194: characters 26-35 : Type not found : PlayState source/FunkinLua.hx:203: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:1883: characters 4-13 : Type not found : PlayState source/FunkinLua.hx:225: characters 26-35 : Type not found : PlayState source/FunkinLua.hx:248: characters 8-17 : Type not found : PlayState source/FunkinLua.hx:1976: characters 10-19 : Type not found : PlayState source/FunkinLua.hx:267: characters 8-17 : Type not found : PlayState source/FunkinLua.hx:350: characters 7-16 : Type not found : PlayState source/FunkinLua.hx:368: characters 7-16 : Type not found : PlayState source/FunkinLua.hx:376: characters 7-16 : Type not found : PlayState source/FunkinLua.hx:387: characters 19-25 : { members : { indexOf : flixel.FlxBasic -> Int } } has no field remove source/FunkinLua.hx:388: characters 19-25 : { members : { indexOf : flixel.FlxBasic -> Int } } has no field insert source/FunkinLua.hx:1765: characters 6-15 : Type not found : PlayState source/FunkinLua.hx:1776: characters 6-15 : Type not found : PlayState source/FunkinLua.hx:1779: characters 6-15 : Type not found : PlayState source/FunkinLua.hx:398: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:411: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:424: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:437: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:450: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:468: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:483: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:486: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:497: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:500: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:511: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:514: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:525: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:528: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:571: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:574: characters 5-14 : Type not found : PlayState s [...]

2022-01-16 17:55 UTC, HiroMizuki commented
> source/Achievements.hx:172: characters 95-104 : Type not found : PlayState source/Achievements.hx:183: characters 119-128 : Type not found : PlayState source/CoolUtil.hx:30: characters 25-34 : Type not found : PlayState source/CoolUtil.hx:46: characters 23-32 : Type not found : PlayState source/WeekData.hx:192: characters 9-18 : Type not found : PlayState source/WeekData.hx:223: characters 20-29 : Type not found : PlayState source/WeekData.hx:228: characters 36-45 : Type not found : PlayState source/FreeplayState.hx:58: characters 3-12 : Type not found : PlayState source/FreeplayState.hx:438: characters 3-12 : Type not found : PlayState source/FreeplayState.hx:377: characters 3-12 : Type not found : PlayState source/FreeplayState.hx:294: characters 5-19 : Type not found : PlayState source/FreeplayState.hx:295: characters 9-23 : Type not found : PlayState source/FreeplayState.hx:301: characters 37-51 : Type not found : PlayState source/FreeplayState.hx:326: characters 4-18 : Type not found : PlayState source/FreeplayState.hx:327: characters 4-13 : Type not found : PlayState source/FreeplayState.hx:328: characters 4-13 : Type not found : PlayState source/FreeplayState.hx:338: characters 41-50 : Type not found : PlayState source/editors/StageEditorState.hx:439: characters 48-57 : Type not found : PlayState source/animateatlas/AtlasFrameMaker.hx:72: characters 6-15 : Type not found : PlayState source/editors/CharacterEditorState.hx:1120: characters 37-46 : Type not found : PlayState source/LoadingState.hx:68: characters 9-23 : Type not found : PlayState source/LoadingState.hx:140: characters 21-35 : Type not found : PlayState source/LoadingState.hx:145: characters 23-37 : Type not found : PlayState source/StoryMenuState.hx:59: characters 3-12 : Type not found : PlayState source/StoryMenuState.hx:398: characters 3-12 : Type not found : PlayState source/StoryMenuState.hx:294: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:295: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:301: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:303: characters 4-18 : Type not found : PlayState source/StoryMenuState.hx:304: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:305: characters 4-13 : Type not found : PlayState source/StoryMenuState.hx:308: characters 41-50 : Type not found : PlayState source/StrumNote.hx:48: characters 6-15 : Type not found : PlayState source/StrumNote.hx:159: characters 47-56 : Type not found : PlayState source/StrumNote.hx:37: characters 6-20 : Type not found : PlayState source/StrumNote.hx:138: characters 46-55 : Type not found : PlayState source/editors/ChartingState.hx:197: characters 7-21 : Type not found : PlayState source/Note.hx:126: characters 36-66 : Type not found : PlayState source/Note.hx:126: characters 69-86 : Type not found : PlayState source/Note.hx:126: characters 8-92 : Cannot add Void and Int source/Note.hx:231: characters 11-25 : Type not found : PlayState source/Note.hx:247: characters 6-15 : Type not found : PlayState source/Note.hx:184: characters 8-17 : Type not found : PlayState source/Note.hx:202: characters 8-17 : Type not found : PlayState source/Note.hx:207: characters 8-17 : Type not found : PlayState source/Note.hx:214: characters 7-16 : Type not found : PlayState source/Note.hx:82: characters 23-37 : Type not found : PlayState source/editors/ChartingState.hx:2632: characters 3-17 : Type not found : PlayState source/editors/ChartingState.hx:423: characters 4-18 : Type not found : PlayState source/editors/ChartingState.hx:573: characters 14-28 : Type not found : PlayState source/editors/ChartingState.hx:1534: characters 5-19 : Type not found : PlayState source/editors/ChartingState.hx:1540: characters 41-50 : Type not found : PlayState source/Shaders.hx:279: characters 3-12 : Type not found : PlayState source/Shaders.hx:461: characters 4-13 : Type not found : PlayState source/Shaders.hx:1002: characters 3-12 : Type not found : PlayState source/Shaders.hx:1048: characters 3-12 : Type not found : PlayState source/Shaders.hx:1098: characters 3-12 : Type not found : PlayState source/FunkinLua.hx:92: characters 14-28 : Type not found : PlayState source/FunkinLua.hx:93: characters 22-36 : Type not found : PlayState source/FunkinLua.hx:97: characters 19-33 : Type not found : PlayState source/FunkinLua.hx💯 characters 22-31 : Type not found : PlayState source/FunkinLua.hx:101: characters 21-30 : Type not found : PlayState source/FunkinLua.hx:102: characters 18-27 : Type not found : PlayState source/FunkinLua.hx:103: characters 34-43 : Type not found : PlayState source/FunkinLua.hx:104: characters 23-32 : Type not found : PlayState source/FunkinLua.hx:136: characters 25-34 : Type not found : PlayState source/FunkinLua.hx:137: characters 25-34 : Type not found : PlayState source/FunkinLua.hx:138: characters 26-35 : Type not found : PlayState source/FunkinLua.hx:139: characters 18-27 : Type not found : PlayState source/FunkinLua.hx:140: characters 19-28 : Type not found : PlayState source/FunkinLua.hx:150: characters 28-37 : Type not found : PlayState source/FunkinLua.hx:151: characters 28-37 : Type not found : PlayState source/FunkinLua.hx:152: characters 27-36 : Type not found : PlayState source/FunkinLua.hx:153: characters 27-36 : Type not found : PlayState source/FunkinLua.hx:154: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:155: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:158: characters 24-38 : Type not found : PlayState source/FunkinLua.hx:159: characters 18-32 : Type not found : PlayState source/FunkinLua.hx:160: characters 17-31 : Type not found : PlayState source/FunkinLua.hx:194: characters 26-35 : Type not found : PlayState source/FunkinLua.hx:203: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:1883: characters 4-13 : Type not found : PlayState source/FunkinLua.hx:225: characters 26-35 : Type not found : PlayState source/FunkinLua.hx:248: characters 8-17 : Type not found : PlayState source/FunkinLua.hx:1976: characters 10-19 : Type not found : PlayState source/FunkinLua.hx:267: characters 8-17 : Type not found : PlayState source/FunkinLua.hx:350: characters 7-16 : Type not found : PlayState source/FunkinLua.hx:368: characters 7-16 : Type not found : PlayState source/FunkinLua.hx:376: characters 7-16 : Type not found : PlayState source/FunkinLua.hx:387: characters 19-25 : { members : { indexOf : flixel.FlxBasic -> Int } } has no field remove source/FunkinLua.hx:388: characters 19-25 : { members : { indexOf : flixel.FlxBasic -> Int } } has no field insert source/FunkinLua.hx:1765: characters 6-15 : Type not found : PlayState source/FunkinLua.hx:1776: characters 6-15 : Type not found : PlayState source/FunkinLua.hx:1779: characters 6-15 : Type not found : PlayState source/FunkinLua.hx:398: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:411: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:424: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:437: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:450: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:468: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:483: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:486: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:497: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:500: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:511: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:514: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:525: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:528: characters 5-14 : Type not found : PlayState source/FunkinLua.hx:571: characters 29-38 : Type not found : PlayState source/FunkinLua.hx:574: characters 5-14 : Type not found : PlayState s [...]

2022-01-16 18:47 UTC, JorgeMiguel22 commented
i guess i builded the wrong way, how you guys puted the stage editor?

2022-01-16 19:08 UTC, HiroMizuki commented
> i guess i builded the wrong way, how you guys puted the stage editor?

i just copied the code to my own source here, u just need to do this at the correct files

2022-01-16 19:14 UTC, JorgeMiguel22 commented
whats the version u used, 0.5.1?

2022-01-16 19:25 UTC, HiroMizuki commented
> 

yes

2022-01-16 19:56 UTC, JorgeMiguel22 commented
when i downloaded the 0.5.1 source and made the EXACT same thing that i made be4 and its compiling

2022-01-16 19:56 UTC, JorgeMiguel22 commented
without errors

2022-01-16 23:06 UTC, magnumsrtisswag commented
soon we are gonna get **lua export support**!

2022-01-17 07:05 UTC, Doritojoey commented
It gets better

2022-01-18 00:41 UTC, PlugBoyOfficial commented
gonna try this out but this looks good rn

2022-01-20 13:24 UTC, MrClogsworthYT commented
a

2022-01-20 13:25 UTC, MrClogsworthYT approved these changes
i approve

2022-02-13 03:13 UTC, Lila-Rogers approved these changes

2022-02-13 08:14 UTC, lsoissus requested changes
maybe, but try adding a option to make it wavy n stuff like you can edit how fast it is n stuff but if you do add it, then ill approve it, im not saying that just for you to add it, it just might be cool for you to add

2022-02-13 08:20 UTC, lsoissus commented
also might try it, lmao

2022-02-13 16:59 UTC, TerrorGaming473 commented
i can use this in my engine (I'll leave the credits)

2022-02-14 08:10 UTC, HiroMizuki approved these changes
i fuckin forgot to approve lmao

2022-02-15 06:56 UTC, TerrorGaming473 commented
i will use this (i will give the credits)

2022-02-17 12:33 UTC, BloxyGames approved these changes
still isnt added, darn it shadowmario this is extremely useful

2022-03-06 14:01 UTC, closed without merging