bbpanzu wanted this
ShadowMario/FNF-PsychEngine pull request #3560
Opened 2022-01-14 17:05 UTC by fireredfan7

2022-01-14 19:29 UTC, tposejank requested changes
Changing UPDATE HAXE TO 4.2.4 is uneccesary.

2022-01-14 19:29 UTC, tposejank commented on UPDATE HAXE TO 4.2.4.txt
> +fireredfan7:
Uneccesary change.

2022-01-14 19:29 UTC, tposejank commented on UPDATE HAXE TO 4.2.4.txt
> +bbpanzu:
Uneccesary change.

2022-01-14 19:37 UTC, nintendofan44 commented on UPDATE HAXE TO 4.2.4.txt
> +bbpanzu:
4.2.0 is bad
this pr is not that bad

2022-01-14 21:52 UTC, Doritojoey commented
There's no point to this

2022-01-15 20:25 UTC, closed without merging

2022-01-15 20:25 UTC, fireredfan7 commented
I see

2022-01-15 22:39 UTC, fireredfan7 commented on UPDATE HAXE TO 4.2.4.txt
> +bbpanzu:
> Changing UPDATE HAXE TO 4.2.4 is uneccesary.

Your'e right.