Disable os, to prevent running raw commandline shit
ShadowMario/FNF-PsychEngine pull request #4006
Opened 2022-01-27 04:35 UTC by superpowers04

2022-01-27 04:41 UTC, Gui-iago approved these changes

2022-01-27 08:00 UTC, Stilic approved these changes
NOT MORE RICKROLL!!!!! (but good for protecting people from any hacker script)

2022-01-27 10:00 UTC, MrClogsworthYT approved these changes
good

2022-01-27 14:33 UTC, tposejank approved these changes
yes

2022-01-27 16:59 UTC, Steviegt6 approved these changes
Looks fine, but I believe this is only really a band-aid fix. Some discussion regarding a plugin permission system may prove useful to allow niche things to still work.

2022-01-27 17:28 UTC, fnaffan29 commented
rip "create text file at the start of the song" command

2022-01-27 17:29 UTC, fnaffan29 commented
nice

2022-01-27 18:18 UTC, cyn-8 requested changes
this change would break the mod im working on since it uses functions like os.clock and os.exit
would it be possible to disable only the potentially malicious functions like os.execute and os.getenv? or is this not possible

like would this work
```
set('os.execute', false);
set('os.getenv', false);
set('os.remove', false);
set('os.rename', false);
set('os.rename', false);
```

2022-01-28 12:10 UTC, tposejank commented
> this change would break the mod im working on since it uses functions like os.clock and os.exit would it be possible to disable only the potentially malicious functions like os.execute and os.getenv? or is this not possible
> 
> like would this work
> 
> ```
> set('os.execute', false);
> set('os.getenv', false);
> set('os.remove', false);
> set('os.rename', false);
> set('os.setlocale', false);
> set('os.tmpname', false);
> ```

malicious intent

2022-01-28 14:12 UTC, Stilic commented
> > this change would break the mod im working on since it uses functions like os.clock and os.exit would it be possible to disable only the potentially malicious functions like os.execute and os.getenv? or is this not possible
> > like would this work
> > ```
> > set('os.execute', false);
> > set('os.getenv', false);
> > set('os.remove', false);
> > set('os.rename', false);
> > set('os.setlocale', false);
> > set('os.tmpname', false);
> > ```
> 
> malicious intent

wdym

2022-01-28 14:15 UTC, superpowers04 commented
> this change would break the mod im working on since it uses functions like os.clock and os.exit would it be possible to disable only the potentially malicious functions like os.execute and os.getenv? or is this not possible
> 
> like would this work
> 
> ```
> set('os.execute', false);
> set('os.getenv', false);
> set('os.remove', false);
> set('os.rename', false);
> set('os.setlocale', false);
> set('os.tmpname', false);
> ```
That did not work sadly

2022-01-28 16:50 UTC, Steviegt6 commented
> > this change would break the mod im working on since it uses functions like os.clock and os.exit would it be possible to disable only the potentially malicious functions like os.execute and os.getenv? or is this not possible
> > like would this work
> > ```
> > set('os.execute', false);
> > set('os.getenv', false);
> > set('os.remove', false);
> > set('os.rename', false);
> > set('os.setlocale', false);
> > set('os.tmpname', false);
> > ```
> 
> That did not work sadly

Would be better for a separate PR, but an alternative solution is manually reimplementing callbacks that replicate various `os` functions as needed.

2022-01-28 18:30 UTC, Stilic commented
> 

i agree

2022-01-29 02:29 UTC, merged