Added more patten way character for playing animation
ShadowMario/FNF-PsychEngine pull request #6922
Opened 2022-03-13 10:02 UTC by afeefflox

basically, I want added as start frame with special animation kind of fun if I added this feature

2022-03-13 11:10 UTC, cyn-8 requested changes
`specialAnim` should be set after `playAnim` is called because the function sets it to `false`

2022-03-13 21:53 UTC, afeefflox commented
> `specialAnim` should be set after `playAnim` is called because the function sets it to `false`

ok I will fixed

2022-03-14 00:08 UTC, cyn-8 approved these changes

2022-03-19 17:09 UTC, superpowers04 approved these changes

2022-07-04 15:37 UTC, closed without merging