nooo moore songname-null!
ShadowMario/FNF-PsychEngine pull request #7931
Opened 2022-04-02 22:33 UTC by mayo78

bruh

2022-04-03 00:02 UTC, Stilic approved these changes

2022-04-03 00:12 UTC, TheKitBoi approved these changes

2022-04-03 09:48 UTC, megasssdev approved these changes

2022-04-04 04:21 UTC, jigsaw-4277821 approved these changes

2022-04-05 06:11 UTC, Raltyro approved these changes

2022-04-08 00:55 UTC, SonicProYT approved these changes

2022-04-09 18:47 UTC, Steviegt6 requested changes
The actual implementation looks fine, but your PR shouldn't change newline formatting. Should go in a different PR.

2022-04-10 18:48 UTC, cyn-8 approved these changes

2022-04-11 15:11 UTC, DM-kun approved these changes

2022-04-11 20:35 UTC, Steviegt6 requested changes

2022-04-11 20:35 UTC, Steviegt6 commented on source/AchievementsMenuState.hx
> -			if(!Achievements.achievementsStuff[i][4] || Achievements.achievementsMap.exists(Achievements.achievementsStuff[i][2])) {
This should go in a different PR.

2022-04-12 15:59 UTC, TBiscuit1 approved these changes
Finally someone added the check in case it's null, thank god

2022-04-13 04:22 UTC, Helisonbr approved these changes

2022-04-16 12:09 UTC, Theoyeah commented
rip mayo is banned

2022-04-28 15:45 UTC, Wither362 approved these changes
I love this!

I approve this!

2022-05-10 16:50 UTC, closed without merging