Automatically grab refresh rate for first time saves
ShadowMario/FNF-PsychEngine pull request #8341
Opened 2022-04-26 02:29 UTC by ActualMandM

This PR makes it so any save created for the first time will have Psych automatically grab the display's refresh rate and set its framerate cap to that, instead of the user having to go into options to set it themselves.

If the monitor's refresh rate is either under or over the FPS cap range, Psych Engine will cap it.

This PR also simplifies the code for setting the framerate cap.

2022-04-27 13:32 UTC, Stilic requested changes
pls make a if else instead

2022-04-27 20:28 UTC, ActualMandM commented
wait shit yeah you can do an if else even with the compiler stuff around it, hold on

2022-05-08 07:30 UTC, Itz-Miles commented
If I have a monitor that's capped at 60Hz, wouldn't this prevent the internal framerate from being over it? I prefer the cool frames number being 120Hz, despite not always testing source on a 120Hz capable display.

2022-05-08 07:50 UTC, ActualMandM commented
It'll only get the monitor's refresh rate when it first creates the save.

2022-05-24 15:54 UTC, lunacynne approved these changes

2022-07-04 15:35 UTC, ShadowMario commented
Revert the change in GraphicsSettingsSubState.hx because it's unnecessary and make it save the framerate to ClientPrefs.framerate

2022-07-04 21:00 UTC, ActualMandM commented
Reverted the GraphicsSettingsSubState change, though I'm confused about the saving to `ClientPrefs.framerate` part. Wouldn't it already be doing that if I'm editing the `framerate` variable within ClientPrefs?

2022-10-29 05:54 UTC, ActualMandM commented
Closing due to no response...

2022-10-29 05:54 UTC, closed without merging

2023-10-08 15:04 UTC, Raltyro commented
sob