gamejolt is shit lol7
ShadowMario/FNF-PsychEngine pull request #8528
Opened 2022-05-07 16:23 UTC by juandavid45

2022-05-07 16:34 UTC, SrtHero278 commented
wrong repository

2022-05-07 19:13 UTC, Joalor64GH commented
tf is wrong with this kid

2022-05-07 20:41 UTC, ManMaster707 requested changes
This kid is CERTAINLY a troll, and if YOU, @juandavid45, are reading this, please, just stop, you're not making anyone's life funnier or easier, you've done this everywhere, even in Kade Engine's pull requests, so stop trying to insert your friends and you in the engine, think about your life decisions, and don't touch github ever again.

2022-05-07 21:45 UTC, SonicProYT commented
oh god the same guy who destroyed the credits

HE DID IT AGAIN

2022-05-07 21:46 UTC, SonicProYT reviewed
SEE?!?
HE RUINED THE CREDITS ONCE AGAIN

2022-05-08 00:10 UTC, voxovistired commented
Never touch GitHub again. Please, it's the best for you and this world.

2022-05-08 00:14 UTC, nintendofan44 reviewed
hell nah
goofy ahh thing

2022-05-08 03:35 UTC, CrusherMods commented
Yo @juandavid45 
please do this its for your own good
![image](https://user-images.githubusercontent.com/90648119/167280649-b96a0674-f707-4c0f-89f6-d01168a89a85.png)

2022-05-08 09:10 UTC, Wither362 commented
Wtf is wrong with you, also you need the icons for the credits, so this code is literally wrong

2022-05-08 12:12 UTC, Joalor64GH commented
that's why i blocked the dummy

2022-05-08 16:21 UTC, Swapper1 commented
I should mention this here. On the Kade Engine's [pull requests page](https://github.com/KadeDev/Kade-Engine/pull/2925), the code was taken from Bob and Bosip mod, where the Story Menu is replace by the Main Menu.
https://github.com/ash237/vs-Bob-and-Bosip/blob/main/source/MainMenuState.hx

2022-05-08 17:34 UTC, SonicProYT commented
should i ask ShadowMario to close this pr and block this kid from the psych repo

this kid ruins psych

2022-05-08 17:34 UTC, SonicProYT commented
(by kid, i mean, the child who made this pr)

2022-05-09 09:24 UTC, Raltyro commented
why the fuck are you making another stupid rep

2022-05-09 13:40 UTC, Theoyeah commented
wrong repo you motherfucker

2022-05-09 13:41 UTC, Theoyeah reviewed
I have your ip stupid kid

2022-05-09 13:41 UTC, Theoyeah commented on source/CreditsState.hx
> +			['Vs Jefferson13n Team'],
Fatherless

2022-05-09 15:21 UTC, closed without merging

2022-05-09 15:23 UTC, CrusherMods commented
YO IT GOT CLOSED AGAIN
LETS PARTY YESSSSSSS

2022-05-09 22:03 UTC, Joalor64GH commented
> YO IT GOT CLOSED AGAIN LETS PARTY YESSSSSSS

F***IN HELL YEAHHHH

2022-05-12 06:24 UTC, Gibberditoslumber commented on source/CreditsState.hx
> +			['Vs Jefferson13n Team'],
DANG NO MERCIY

2022-07-13 04:39 UTC, REALHaydenGaming commented
YEAH, FATHERLESS RETARD GETS HIS PULL REQUEST DOWN