Created a screen shake option for those who sensive to shake
ShadowMario/FNF-PsychEngine pull request #9830
Opened 2022-07-20 20:38 UTC by EpokCoolGuy

Hi, this pull request is about make a screen shake option for pepole who is sensive to shake

PD:some mods have it, so don't say is useless

2022-07-20 20:45 UTC, DillyzThe1 commented
You also need to disable shaking in [FunkinLua.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx#L1514).

2022-07-20 20:47 UTC, EpokCoolGuy commented
> You also need to disable shaking in [FunkinLua.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx#L1514).

thank's i forgot

2022-07-21 15:21 UTC, DillyzThe1 commented
> > You also need to disable shaking in [FunkinLua.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx#L1514).
> 
> thank's i forgot

np

2022-07-21 15:25 UTC, DillyzThe1 commented
Also, you might want to change your implementation in FunkinLua.hx.
You see, you might cause mods to call a null function, when in reality you want to put _if(ClientPrefs.shaking)_ above _cameraFromString(camera).shake(intensity, duration);_.

Example:

`Lua_helper.add_callback(lua, "cameraShake", function(camera:String, intensity:Float, duration:Float) {
             if(ClientPrefs.shaking)
                        cameraFromString(camera).shake(intensity, duration);
});`

2022-07-21 15:51 UTC, Paracosm-Daemon commented
i think you could rename it to "reduced motion" since it's more descriptive about motion + correlates with things like motion sickness more

2022-07-22 02:16 UTC, MemeHoovy approved these changes
I know some mods that use this so this could be useful.

2022-07-22 04:24 UTC, DaRealDotZ approved these changes
Much Needed Option

2022-07-22 09:48 UTC, Paracosm-Daemon approved these changes

2022-07-27 10:17 UTC, l1ttleO requested changes

2022-07-27 10:17 UTC, l1ttleO commented on source/ClientPrefs.hx
> +        public static var shaking:Bool = true
```suggestion
        public static var shaking:Bool = true;
```

2022-07-27 10:17 UTC, l1ttleO commented on source/PlayState.hx
> +		if(ClientPrefs.shaking) {
```suggestion
			if(ClientPrefs.shaking) {
```
some indenting please

2022-07-27 10:17 UTC, l1ttleO commented on source/PlayState.hx
> +		}
```suggestion
			}
```
some indenting please

2022-07-27 10:17 UTC, l1ttleO commented on source/FunkinLua.hx
> +			});
```suggestion
		Lua_helper.add_callback(lua, "cameraShake", function(camera:String, intensity:Float, duration:Float) {
			if(ClientPrefs.shaking) cameraFromString(camera).shake(intensity, duration); 
		});
```

2022-07-27 10:17 UTC, l1ttleO commented on source/options/VisualsUISubState.hx
> +			true);
```suggestion
		var option:Option = new Option('Screen Shake',
		"Uncheck this if you're sensitive to shake!",
		'shaking',
		'bool',
		true);
```

2022-09-27 22:16 UTC, TheAverageGitHubUser commented
making it for another pull

2022-09-27 22:17 UTC, TheAverageGitHubUser commented on source/PlayState.hx
> +		if(ClientPrefs.shaking) {
bruh

2022-10-23 19:05 UTC, closed without merging